name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - master
    # tags:
    #   - v\d+\.\d+\.\d+

env:
  PROJECT_ID: devops-storybooks-391700

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set ENVIRONMENT
        run: |-
          if [ ${GITHUB_REF##*/} = "master" ]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          else 
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          fi

      # Install Python 3.9
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Set python in path
      - name: Export gcloud related env variable
        run: export CLOUDSDK_PYTHON="/usr/bin/python3"

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI with the provided credentials in the ubuntu-latest defined above
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: '318.0.0'
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
      
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          make push

      - name: Deploy
        run: |-
          make deploy